include:
  - project: 'WWU-IT/ci-templates'
    file: '.gitlab-ci-helm.yml'
    ref: 'v12'

test charts:
  image:
    name: harbor.uni-muenster.de/proxy-docker/library/alpine:3.16.2
  stage: test
  variables:
    helm_version: 3.10.0
  tags:
    - autoscaling
    - mike
  before_script:
    - apk add curl
    - curl -L "https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz" | tar zxf - -C /usr/local/bin kubeval
    - curl -L "https://get.helm.sh/helm-v${helm_version}-linux-amd64.tar.gz" | tar zxf - -C /usr/local/bin --strip-components=1 linux-amd64/helm
  script:
    - chmod +x ./ci-scripts/chart-test.sh > /dev/null
    - chmod go-r /builds/sciebo-rds/charts.tmp/KUBECONFIG > /dev/null
    - ./ci-scripts/chart-test.sh
  rules:
    - changes: 
      - charts/**/*

deploy charts to harbor:
  image:
    name: harbor.uni-muenster.de/proxy-docker/library/alpine:3.16.2
  stage: deploy
  variables:
    helm_version: 3.10.0
  tags:
    - autoscaling
    - mike
  before_script:
    - apk add curl jq python3 py3-pip
    - curl -L "https://get.helm.sh/helm-v${helm_version}-linux-amd64.tar.gz" | tar zxf - -C /usr/local/bin --strip-components=1 linux-amd64/helm
    - pip install yq
  script:
    - chmod +x ./ci-scripts/chart-deploy.sh > /dev/null
    - chmod go-r /builds/sciebo-rds/charts.tmp/KUBECONFIG > /dev/null
    - ./ci-scripts/chart-deploy.sh
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "release"'
    - if: '$CI_COMMIT_TAG'
