include:
  - project: 'WWU-IT/ci-templates'
    file: '.gitlab-ci-helm.yml'
    ref: 'v12'

chart-test-all:
  extends: .helm-test
  allow_failure: true
  variables:
    directory: charts/all

chart-test-common:
  extends: .helm-test
  allow_failure: true
  variables:
    directory: charts/common

chart-test-jaeger:
  extends: .helm-test
  allow_failure: true
  variables:
    directory: charts/jaeger

chart-test-layer0_describo:
  extends: .helm-test
  allow_failure: true
  variables:
    directory: charts/layer0_describo

chart-test-layer0_helper_describo_token_updater:
  extends: .helm-test
  allow_failure: true
  variables:
    directory: charts/layer0_helper_describo_token_updater

chart-test-layer0_web:
  extends: .helm-test
  allow_failure: true
  variables:
    directory: charts/layer0_web

chart-test-layer1_port_openscienceframework:
  extends: .helm-test
  allow_failure: true
  variables:
    directory: charts/layer1_port_openscienceframework

chart-test-layer1_port_owncloud:
  extends: .helm-test
  allow_failure: true
  variables:
    directory: charts/layer1_port_owncloud

chart-test-layer1_port_reva:
  extends: .helm-test
  allow_failure: true
  variables:
    directory: charts/layer1_port_reva

chart-test-layer1_port_zenodo:
  extends: .helm-test
  allow_failure: true
  variables:
    directory: charts/layer1_port_zenodo

chart-test-layer2_exporter_service:
  extends: .helm-test
  allow_failure: true
  variables:
    directory: charts/layer2_exporter_service

chart-test-layer2_metadata_service:
  extends: .helm-test
  allow_failure: true
  variables:
    directory: charts/layer2_metadata_service

chart-test-layer2_port_service:
  extends: .helm-test
  allow_failure: true
  variables:
    directory: charts/layer2_port_service

chart-test-layer3_research_manager:
  extends: .helm-test
  allow_failure: true
  variables:
    directory: charts/layer3_research_manager

chart-test-layer3_token_storage:
  extends: .helm-test
  allow_failure: true
  variables:
    directory: charts/layer3_token_storage

chart-test-postgresql:
  extends: .helm-test
  allow_failure: true
  variables:
    directory: charts/postgresql

chart-test-redis:
  extends: .helm-test
  allow_failure: true
  variables:
    directory: charts/redis

chart-test-redis-cluster:
  extends: .helm-test
  allow_failure: true
  variables:
    directory: charts/redis-cluster

charts:
  stage: deploy
  image: harbor.uni-muenster.de/rds/skaffold:testing
  variables:
    HELM_BRANCH: develop
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "release"'
    - if: '$CI_COMMIT_TAG'
      variables:
        HELM_BRANCH: stable
  script:
    - mkdir -p ./pkgs
    - helm plugin install https://github.com/chartmuseum/helm-push.git
    - helm repo add --username gitlab-ci-token --password ${CI_JOB_TOKEN} ${CI_PROJECT_NAME} ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/${HELM_BRANCH}
    - for i in charts/*/;do helm cm-push --force "$i" ${CI_PROJECT_NAME} ;done

charts_pages:
  stage: build
  image: harbor.uni-muenster.de/rds/skaffold:testing
  variables:
    HELM_BRANCH: develop
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "release"'
      variables:
        HELM_BRANCH: stable
    - if: '$CI_COMMIT_TAG'
      variables:
        HELM_BRANCH: stable
  script:
    - apt update
    - apt install -y python3 python3-pip
    - pip3 install awscli
    - mkdir -p ./docs/static/charts
    - aws --endpoint-url https://radosgw.public.os.wwu.de s3 cp s3://sciebords-charts/${HELM_BRANCH} ./docs/static/charts --recursive
    - find charts -name Chart.yaml -print | sed s/Chart.yaml//g | awk -F"/" '{print NF $0}' | sort -nr | sed 's/^.//' | xargs -n1 helm dep build
    - for i in charts/*/;do helm package --dependency-update --destination ./docs/static/charts "$i" ;done
    - helm repo index --url https://www.research-data-services.org/charts/${HELM_BRANCH} --merge ./docs/static/charts/index.yaml ./docs/static/charts/
    - aws --endpoint-url https://radosgw.public.os.wwu.de s3 cp ./docs/static/charts s3://sciebords-charts/${HELM_BRANCH} --recursive

# TODO: We should get rid of skaffold
deploy:
  extends: .deploy
  image: harbor.uni-muenster.de/rds/skaffold:testing
  rules:
  - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  - if: '$CI_COMMIT_BRANCH == "release"'
  - if: '$CI_COMMIT_TAG'
  script:
    - mkdir -p ~/.config/sops/age
    - cat "$AGE_KEYS" | base64 -d - > ~/.config/sops/age/keys.txt
    - mkdir -p ~/.kube
    - cat "$KUBE_CONFIG" | base64 -d - > ~/.kube/config
    - export KUBECONFIG=~/.kube/config
    # reduce noise in ci
    - chmod go-r ~/.kube/config
    # pull helm deps: https://github.com/helm/helm/issues/2247#issuecomment-998636912
    # workaround issue #206
    - helm delete sciebords || true
    # workaround due to old deploy cluster
    - sed -i -e 's#networking.k8s.io/v1#extensions/v1beta1#g' ./charts/*/templates/ingress.yaml
    - sed -i -e '22d' ./charts/*/templates/ingress.yaml
    - sed -i -e '24,28d' ./charts/*/templates/ingress.yaml
    - > 
      sed -i -e '$ a\              serviceName: {{ $fullName }}' ./charts/*/templates/ingress.yaml
    - >
      sed -i -e '$ a\              servicePort: http' ./charts/*/templates/ingress.yaml
    # shotgun debugging ftw
    - cat ./charts/*/templates/ingress.yaml
    # lol that was fun
    # turns out colons in commands are interpreted by gitlab ci
    - find ./charts -name Chart.yaml -print | sed s/Chart.yaml//g | awk -F"/" '{print NF $0}' | sort -nr | sed 's/^.//' | xargs -n1 helm dep build
    - helm secrets upgrade -i sciebords charts/all --values $HELM_DEPLOY_VALUES --set-string global.image.tag=$CI_PIPELINE_ID
    # now try to write everything out in our super secret repo
    - git config --global user.name "CI Update User"
    - git config --global user.email "sciebo.rds@wwu.de"
    - git clone "https://${SCIEBO_RDS_TEST_DEPLOY_NAME}:${SCIEBO_RDS_TEST_DEPLOY_TOKEN}@zivgitlab.uni-muenster.de/wwuit-sys/sciebo/applications/rds-test.git" --branch "develop"
    - cd rds-test
    - mkdir -p deploy
    - helm secrets template sciebords ../charts/all --values $HELM_DEPLOY_VALUES --set-string global.image.tag=$CI_PIPELINE_ID | sed -e 's/sciebo-rds-dev/rds-test/g' > deploy/rds-test.yml
    - git add deploy
    - git commit -m "Automatic update"
    - git push "https://${SCIEBO_RDS_TEST_DEPLOY_NAME}:${SCIEBO_RDS_TEST_DEPLOY_TOKEN}@zivgitlab.uni-muenster.de/wwuit-sys/sciebo/applications/rds-test.git" "develop:develop"

