apiVersion: v1
kind: ConfigMap
metadata:
  name: layer3researchconfig
  namespace: {{ .Release.Namespace  }}
data:
  REDIS_HOST: {{ .Values.environment.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.environment.REDIS_PORT | quote }}